In [218]:
import pandas as pd
import numpy as np

In [215]:
class FileValidationError(Exception):
    """Incase file not found or doesnt exist!"""
    pass
class FileMissingValueError(FileValidationError):
    """If file exists but contains no value at all!"""
    pass

def load_results(filepath: str):
    if not os.path.exists(filepath):
        raise FileValidationError("File not found!!")  
    
    elif os.path.getsize(filepath) == 0:
        raise FileMissingValueError("File exists but contain no value or data")

    else:
        return pd.read_csv(filepath, na_values=["\\N"])
        
def filter_by_points_range(df: pd.DataFrame, min_points: int, max_points: int) -> pd.DataFrame:
    return df.query("points >= @min_points & points <= @max_points")

def filter_by_grid_and_position(df: pd.DataFrame, grid_positions: list[int], finish_positions: list[str]) -> pd.DataFrame:
    return df[df["grid"].isin(grid_positions) & df["position"].isin(finish_positions)]

df = load_results("../data/pandas_p1/results.csv")

print(df)

print(df.shape)

print(filter_by_points_range(df, min_points=10, max_points=25))

print(filter_by_grid_and_position(df, grid_positions=[1], finish_positions=["1"]))

       resultId  raceId  driverId  constructorId  number  grid  position  \
0             1      18         1              1    22.0     1       1.0
1             2      18         2              2     3.0     5       2.0
2             3      18         3              3     7.0     7       3.0
3             4      18         4              4     5.0    11       4.0
4             5      18         5              1    23.0     3       5.0
...         ...     ...       ...            ...     ...   ...       ...
26754     26760    1144       825            210    20.0    14      16.0
26755     26761    1144       859            215    30.0    12      17.0
26756     26762    1144       822             15    77.0     9       NaN
26757     26763    1144       861              3    43.0    20       NaN
26758     26764    1144       815              9    11.0    10       NaN

      positionText  positionOrder  points  laps         time  milliseconds  \
0                1              1    10.0    58  1:34:50.616     5690616.0
1                2              2     8.0    58       +5.478     5696094.0
2                3              3     6.0    58       +8.163     5698779.0
3                4              4     5.0    58      +17.181     5707797.0
4                5              5     4.0    58      +18.014     5708630.0
...            ...            ...     ...   ...          ...           ...
26754           16             16     0.0    57          NaN           NaN
26755           17             17     0.0    55          NaN           NaN
26756            R             18     0.0    30          NaN           NaN
26757            R             19     0.0    26          NaN           NaN
26758            R             20     0.0     0          NaN           NaN

       fastestLap  rank fastestLapTime  fastestLapSpeed  statusId
0            39.0   2.0       1:27.452          218.300         1
1            41.0   3.0       1:27.739          217.586         1
2            41.0   5.0       1:28.090          216.719         1
3            58.0   7.0       1:28.603          215.464         1
4            43.0   1.0       1:27.418          218.385         1
...           ...   ...            ...              ...       ...
26754        57.0   1.0       1:25.637          222.002        11
26755        52.0  12.0       1:28.751          214.212         5
26756        14.0  19.0       1:29.482          212.462       130
26757         5.0  17.0       1:29.411          212.631         5
26758         NaN   0.0            NaN              NaN         4

[26759 rows x 18 columns]
(26759, 18)
       resultId  raceId  driverId  constructorId  number  grid  position  \
0             1      18         1              1    22.0     1       1.0
22           23      19         8              6     1.0     2       1.0
44           45      20        13              6     2.0     2       1.0
66           67      21         8              6     1.0     1       1.0
88           89      22        13              6     2.0     1       1.0
...         ...     ...       ...            ...     ...   ...       ...
26739     26745    1144       846              1     4.0     1       1.0
26740     26746    1144       832              6    55.0     3       2.0
26741     26747    1144       844              6    16.0    19       3.0
26742     26748    1144         1            131    44.0    16       4.0
26743     26749    1144       847            131    63.0     6       5.0

      positionText  positionOrder  points  laps         time  milliseconds  \
0                1              1    10.0    58  1:34:50.616     5690616.0
22               1              1    10.0    56  1:31:18.555     5478555.0
44               1              1    10.0    57  1:31:06.970     5466970.0
66               1              1    10.0    66  1:38:19.051     5899051.0
88               1              1    10.0    58  1:26:49.451     5209451.0
...            ...            ...     ...   ...          ...           ...
26739            1              1    25.0    58  1:26:33.291     5193291.0
26740            2              2    18.0    58       +5.832     5199123.0
26741            3              3    15.0    58      +31.928     5225219.0
26742            4              4    12.0    58      +36.483     5229774.0
26743            5              5    10.0    58      +37.538     5230829.0

       fastestLap  rank fastestLapTime  fastestLapSpeed  statusId
0            39.0   2.0       1:27.452          218.300         1
22           37.0   2.0       1:35.405          209.158         1
44           38.0   3.0       1:33.600          208.153         1
66           46.0   1.0       1:21.670          205.191         1
88           16.0   3.0       1:26.666          221.734         1
...           ...   ...            ...              ...       ...
26739        52.0   3.0       1:27.438          217.429         1
26740        55.0   5.0       1:27.765          216.619         1
26741        51.0   9.0       1:28.018          215.996         1
26742        44.0   2.0       1:27.278          217.828         1
26743        56.0  10.0       1:28.195          215.563         1

[1801 rows x 18 columns]
Empty DataFrame
Columns: [resultId, raceId, driverId, constructorId, number, grid, position, positionText, positionOrder, points, laps, time, milliseconds, fastestLap, rank, fastestLapTime, fastestLapSpeed, statusId]
Index: []

In [232]:
df = load_results("../data/pandas_p1/results.csv")
df.replace("\\N", np.nan)

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22.0,1,1.0,1,1,10.0,58,1:34:50.616,5690616.0,39.0,2.0,1:27.452,218.300,1
1,2,18,2,2,3.0,5,2.0,2,2,8.0,58,+5.478,5696094.0,41.0,3.0,1:27.739,217.586,1
2,3,18,3,3,7.0,7,3.0,3,3,6.0,58,+8.163,5698779.0,41.0,5.0,1:28.090,216.719,1
3,4,18,4,4,5.0,11,4.0,4,4,5.0,58,+17.181,5707797.0,58.0,7.0,1:28.603,215.464,1
4,5,18,5,1,23.0,3,5.0,5,5,4.0,58,+18.014,5708630.0,43.0,1.0,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26754,26760,1144,825,210,20.0,14,16.0,16,16,0.0,57,NaN,NaN,57.0,1.0,1:25.637,222.002,11
26755,26761,1144,859,215,30.0,12,17.0,17,17,0.0,55,NaN,NaN,52.0,12.0,1:28.751,214.212,5
26756,26762,1144,822,15,77.0,9,NaN,R,18,0.0,30,NaN,NaN,14.0,19.0,1:29.482,212.462,130
26757,26763,1144,861,3,43.0,20,NaN,R,19,0.0,26,NaN,NaN,5.0,17.0,1:29.411,212.631,5
26758,26764,1144,815,9,11.0,10,NaN,R,20,0.0,0,NaN,NaN,NaN,0.0,NaN,NaN,4

In [238]:
def handle_missing_values(df: pd.DataFrame, strategy: str="drop") -> pd.DataFrame:
    if strategy == "drop":
        df = df.dropna()
    elif strategy == "fill":
        df = df.fillna(df.select_dtypes(include="number").mean())
    else: print("Wrong Message!!")
    return df

df = handling_missing_values(df, "drop")

In [234]:
def remove_duplicates(df: pd.DataFrame) -> pd.DataFrame:
    return df.drop_duplicates()

df = remove_duplicates(df)

In [239]:
def fix_dtypes(df, column, target_type) -> pd.DataFrame:
    df[column] = pd.to_numeric(df[column], errors="coerce")
    return df

fix_dtypes(df, "points", "float64")

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22.0,1,1.0,1,1,10.0,58,1:34:50.616,5690616.0,39.0,2.0,1:27.452,218.300,1
1,2,18,2,2,3.0,5,2.0,2,2,8.0,58,+5.478,5696094.0,41.0,3.0,1:27.739,217.586,1
2,3,18,3,3,7.0,7,3.0,3,3,6.0,58,+8.163,5698779.0,41.0,5.0,1:28.090,216.719,1
3,4,18,4,4,5.0,11,4.0,4,4,5.0,58,+17.181,5707797.0,58.0,7.0,1:28.603,215.464,1
4,5,18,5,1,23.0,3,5.0,5,5,4.0,58,+18.014,5708630.0,43.0,1.0,1:27.418,218.385,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26744,26750,1144,830,9,1.0,4,6.0,6,6,8.0,58,+49.847,5243138.0,56.0,6.0,1:27.765,216.619,1
26745,26751,1144,842,214,10.0,5,7.0,7,7,6.0,58,+1:12.560,5265851.0,30.0,16.0,1:29.251,213.012,1
26746,26752,1144,807,210,27.0,7,8.0,8,8,4.0,58,+1:15.554,5268845.0,17.0,14.0,1:29.152,213.249,1
26747,26753,1144,4,117,14.0,8,9.0,9,9,2.0,58,+1:22.373,5275664.0,51.0,7.0,1:27.948,216.168,1
26748,26754,1144,857,1,81.0,2,10.0,10,10,1.0,58,+1:23.821,5277112.0,51.0,4.0,1:27.690,216.804,1

In [253]:
def clean_string_column(df: pd.DataFrame, columns: str) -> pd.DataFrame:
    df[columns] = df[columns].str.strip().str.lower()
    return df

df = clean_string_columns(df, "surname")

TypeError: clean_string_column() missing 1 required positional argument: 'columns'

In [248]:
dd

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44.0,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,NaN,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6.0,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14.0,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,NaN,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...,...
856,858,sargeant,2.0,SAR,Logan,Sargeant,2000-12-31,American,http://en.wikipedia.org/wiki/Logan_Sargeant
857,859,lawson,30.0,LAW,Liam,Lawson,2002-02-11,New Zealander,http://en.wikipedia.org/wiki/Liam_Lawson
858,860,bearman,38.0,BEA,Oliver,Bearman,2005-05-08,British,http://en.wikipedia.org/wiki/Oliver_Bearman
859,861,colapinto,43.0,COL,Franco,Colapinto,2003-05-27,Argentinian,http://en.wikipedia.org/wiki/Franco_Colapinto
860,862,doohan,61.0,DOO,Jack,Doohan,2003-01-20,Australian,http://en.wikipedia.org/wiki/Jack_Doohan